# Generated by Django 6.0.4 on 2026-04-30 01:03

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
