# Generated by Django 6.0.4 on 2026-05-01 16:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'База знаний',
                'verbose_name_plural': 'Базы знаний',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='adminp_know_search__d361d2_gin')],
            },
        ),
    ]
