# Generated by Django 6.0.4 on 2026-05-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0003_add_search_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TRIGGER IF EXISTS search_vector_update ON adminp_knowledgebase;',
        ),
        migrations.RunSQL(
            sql='''
                CREATE TRIGGER search_vector_update BEFORE INSERT OR UPDATE
                ON adminp_knowledgebase
                FOR EACH ROW EXECUTE FUNCTION
                tsvector_update_trigger(search_vector, 'pg_catalog.russian', question);
            ''',
            reverse_sql='DROP TRIGGER IF EXISTS search_vector_update ON adminp_knowledgebase;'
        ),
    ]
