# Generated by Django 6.0.4 on 2026-05-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0004_search_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bot_files/', verbose_name='Прикреплённый файл'),
        ),
    ]
