# Generated by Django 6.0.4 on 2026-05-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0005_knowledgebase_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user_id', models.CharField(max_length=100, unique=True, verbose_name='ID в MAX')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('applicant', 'Абитуриент')], max_length=20, verbose_name='Роль')),
                ('group_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер группы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь MAX',
                'verbose_name_plural': 'Пользователи MAX',
            },
        ),
    ]
