# Generated by Django 6.0.4 on 2026-05-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0006_botuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='target_groups',
            field=models.CharField(blank=True, help_text='Оставьте пустым, если вопрос для всех групп этой роли', max_length=255, null=True, verbose_name='Для каких групп (через запятую)'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='visibility',
            field=models.CharField(choices=[('all', 'Для всех'), ('student', 'Только студентам'), ('applicant', 'Только абитуриентам')], default='all', max_length=20, verbose_name='Кому доступен'),
        ),
    ]
