# Generated by Django 6.0.4 on 2026-05-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0007_knowledgebase_target_groups_knowledgebase_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение от пользователя')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='Ответ администратора')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Отвечено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminp.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
