# Generated by Django 6.0.4 on 2026-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='is_faq',
            field=models.BooleanField(default=False, verbose_name='Показывать в частых вопросах'),
        ),
    ]
