# Generated by Django 6.0.4 on 2026-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0009_knowledgebase_is_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название группы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Учебные группы',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
    ]
