# Generated by Django 6.0.4 on 2026-05-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0010_universitygroups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'verbose_name': 'Список вопросов', 'verbose_name_plural': 'Список вопросов'},
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='target_groups',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='target_groups',
            field=models.ManyToManyField(blank=True, help_text="Выберите группы (в т.ч. 'Абитуриенты'). Если пусто — доступно всем.", to='adminp.universitygroups', verbose_name='Кому доступен вопрос'),
        ),
    ]
