# Generated by Django 6.0.4 on 2026-05-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0011_alter_knowledgebase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователи MAX', 'verbose_name_plural': 'Пользователи MAX'},
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='role',
        ),
        migrations.AddField(
            model_name='botuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='adminp.universitygroups', verbose_name='Группа'),
        ),
    ]
