# Generated by Django 6.0.4 on 2026-05-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0012_alter_botuser_options_remove_botuser_group_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователя MAX', 'verbose_name_plural': 'Пользователи MAX'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Список вопросов'},
        ),
        migrations.AlterModelOptions(
            name='universitygroups',
            options={'verbose_name': 'Учебную группу', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_replied',
            field=models.BooleanField(default=False, editable=False, verbose_name='Отвечено'),
        ),
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема/Название рассылки')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('is_sent', models.BooleanField(default=False, editable=False, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('target_groups', models.ManyToManyField(help_text='Сообщение получат все пользователи, состоящие в выбранных группах', to='adminp.universitygroups', verbose_name='Группы для рассылки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Массовые рассылки',
            },
        ),
        migrations.CreateModel(
            name='UserQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=255, verbose_name='Текст запроса')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Ответ найден')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminp.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог запроса пользователя',
                'verbose_name_plural': 'Логи запросов пользователей',
            },
        ),
    ]
