# Generated by Django 6.0.4 on 2026-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0013_alter_botuser_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Вносите слова в нижнем регистре и в начальной форме', max_length=100, unique=True, verbose_name='Запрещенное слово')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Запрещенное слово',
                'verbose_name_plural': 'Запрещенные слова',
                'ordering': ['word'],
            },
        ),
        migrations.AlterModelOptions(
            name='massnotification',
            options={'verbose_name': 'Рассылку', 'verbose_name_plural': 'Массовые рассылки'},
        ),
        migrations.AlterModelOptions(
            name='userquerylog',
            options={'verbose_name': 'Лог запроса', 'verbose_name_plural': 'Логи запросов'},
        ),
    ]
