# Generated by Django 6.0.4 on 2026-05-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0014_bannedword_alter_massnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedword',
            options={'ordering': ['word'], 'verbose_name': 'Запрещенное слово', 'verbose_name_plural': '6.Запрещенные слова'},
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователя MAX', 'verbose_name_plural': '4.Пользователи MAX'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': '1.Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': '3.Список вопросов'},
        ),
        migrations.AlterModelOptions(
            name='massnotification',
            options={'verbose_name': 'Рассылку', 'verbose_name_plural': '2.Массовые рассылки'},
        ),
        migrations.AlterModelOptions(
            name='universitygroups',
            options={'verbose_name': 'Учебную группу', 'verbose_name_plural': '5.Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='userquerylog',
            options={'verbose_name': 'Лог запроса', 'verbose_name_plural': '7.Логи запросов'},
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='faq_question',
            field=models.CharField(default='Тест', max_length=255, verbose_name='Расширенный вопрос'),
            preserve_default=False,
        ),
    ]
