# Generated by Django 6.0.4 on 2026-05-30 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0015_alter_bannedword_options_alter_botuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquerylog',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminp.knowledgebase', verbose_name='Найденный ответ'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='faq_question',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='question',
            field=models.TextField(verbose_name='Расширенный вопрос'),
        ),
    ]
