# Generated by Django 6.0.4 on 2026-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0016_userquerylog_knowledge_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_file',
            field=models.FileField(blank=True, null=True, upload_to='feedback_replies/', verbose_name='Прикреплённый файл'),
        ),
        migrations.AddField(
            model_name='massnotification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notifications/', verbose_name='Прикреплённый файл'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_base_files/', verbose_name='Прикреплённый файл'),
        ),
    ]
