# Generated by Django 6.0.4 on 2026-06-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0017_feedback_admin_file_massnotification_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin_file',
        ),
        migrations.RemoveField(
            model_name='massnotification',
            name='file',
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bot_files/', verbose_name='Прикреплённый файл'),
        ),
    ]
